### ISSUE TITLE
Freetem rewards not working

### ISSUE THREAD

**Issue by BenMasel** [maael/temtem-api#105] opened 2021-12-22 14:30 UTC

**Comment by maael** [comment] 2021-12-23 00:11
This is due to the wiki changing format, meaning the collection isn't working as expected. Not sure when I'll be able to look at this I'm afraid, but feel free to take a look to see if you can fix it in the mean time, I'm happy to give pointers, just ask. 👍

**Comment by arossetter** [comment] 2021-12-23 00:58
I took a super quick look at this.. Looks like the table was pushed further away from the rewards header than it used to be. Though instead of playing the DOM games this time, I went and edited the wiki itself. :) The table that holds the FreeTem rewards now has an id! SHOULD make it so that line 17 of getFreeTamRewards.ts needs to read:

const tableRows = $("#rewards-curr-table").find("tr");

(At least until an admin looks at my anonymous edit and changes it back)

I'm going to wait a couple days to see if they let my little edit slide and if they do I'll create a branch. In the meantime it looks like if you want to keep doing DOM acrobatics it might work with this (@BenMasel if you want a crack at debugging typescript,.. :)) :

const tableRows = $("#Rewards").parent().next().next().next().next().find("tr");

@maael  not sure if you heard but with the Arbury release Crema is pushing out an API of their own. They haven't really clarified any real information about what exactly it is (like I don't know if it's based on the player or a global data API similar to yours), but I'll keep my ear to the ground and can provide info when new patches come out that explain it better.

**Comment by arossetter** [comment] 2021-12-23 01:07
Also duplicate of #30

**Comment by arossetter** [comment] 2021-12-27 01:46
Hey all,

I haven't forgotten about this. Hit a small roadblock, however, in that the table seems to have changed more than I'd originally anticipated. 

In short, it looks like where we were originally expecting a single row for each object, there are now two rows, so the parsing logic will need to be updated to match. I can do this but I'll need to try and make some time this week as I am one of the unfortunate fools that actually is working this week.

**Comment by maael** [comment] 2021-12-27 11:34
Hey @arossetter, thanks for taking a look at this! I've only just seen your replies, been pretty unplugged over Christmas. 

I think the DOM acrobatics are still needed for the past rewards, but that ID was handy for the current rewards, I think I've patched something up here: https://github.com/maael/temtem-api/pull/106 that seems to work and restore the data at least. 

I'm really sorry to have doubled up the work with you here, if you've done it in a better way, it would be great to have, or still great to see how you took a crack at it. Any questions or things you think could be done different in #106 would be great to hear too. I definitely need to start comment the logic in the scripts to make it easier to see what's happening, takes me a bit to get back on top of it when I come back to this project. 😄 

I think I'm going to go ahead and merge that PR just to get some data back on the API, but I'm happy to change it when you've had a chance to look.

I hadn't heard about Crema doing their own API! I haven't had much time to play Temtem much recently. That's cool to hear though, thanks for letting me know. I imagine they'll do some cool things that we just can't do, the post that talks about it says things like accessing Auction House data and encounters! We'll keep an eye on it.

**Comment by arossetter** [comment] 2021-12-27 13:27
So a little background on me: I'm actually a desktop application developer, more into the C variants as far as languages go. Whenever I look at something on this project I'm effectively having to relearn JS and TS all over again every time. I'm sure what you put in is probably going to be leagues better than anything I can do in a fraction of the time. 😄 

Though I do have a separate issue I discovered, along with a fix for said issue, while debugging this. I'll post a new issue for it.

**Comment by maael** [comment] 2021-12-29 16:05
No worries! Sounds pretty much like me whenever I try to do desktop application things (most of the time I cheat and try to use web things like [nw.js](https://nwjs.io/) to get around it. 😄 

If you do want to pick up anything to work on, feel free to! I'm happy to review in progress things too if you open early/draft PRs. If you let me know you're working on anything, I'll keep a better eye out in the future too so we don't double up.

I'm going to go ahead and close this specific issue as it all seems okay now.

**Closed by maael** 2021-12-29 16:05 UTC
Labels: bug, help wanted, data issue, data: freetem rewards

**Comment by BenMasel** [comment] 2022-01-12 02:59
Hey again! So I may be wrong but I think that although the API is working, it's not showing the latest data.

Hope this helps xD
